name: compenv
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip>=23
  - numpy>=1.26,<2
  - scipy>=1.11
  - pandas>=2.0
  - scikit-learn>=1.3
  - numba
  - h5py
  - tqdm
  - matplotlib>=3.8
  - seaborn>=0.13
  - jupyterlab
  - notebook
  - ipykernel
  - ipywidgets
  - pillow
  - requests
  - setuptools<81
  - pytorch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - pytorch-cuda=11.8
  - torchsde=0.2.6
  - pip:
      - einops==0.7.0
      - pytorch-lightning==1.9.5
      - torchdiffeq==0.2.3
      - torchcde==0.2.5
      - torchcfm==1.0.5
      - torchdyn==1.0.6
      - torchmetrics==1.3.0
      - normflows==1.7.3
      - zenodo-get==1.6.1
